name: climpca
channels:
  - conda-forge
  - nvidia
  - rapidsai
  - defaults
dependencies:
  - python>=3.9.13
  - tqdm>=4.64.1
  - cuml>=22.10.00
  - numpy>=1.23.4
  - xarray>=2022.10.0
  - netcdf4>=1.5.7